package seng4430.metricProviders;

import com.github.javaparser.ast.CompilationUnit;

import java.util.List;

/**
 * Base class all MetricProviders should inherit from.
 * Provides methods required for running analysis against compiled java classes.
 */
public abstract class MetricProvider {
    /**
     * @param compilationUnits All parsed compilation units to run analysis against
     * @param configuration    Configuration object to use for anaylsis
     * @return A MetricResultSet containing the set of results generated by analysis
     */
    public abstract MetricResultSet runAnalysis(List<CompilationUnit> compilationUnits, AnalysisConfiguration configuration);

    /**
     * @return The name of the metric the provider is analysing against.
     */
    public abstract String metricName();

    /**
     * @param compilationUnits All parsed compilation units to run analysis against
     * @return A MetricResultSet containing the set of results generated by analysis
     */
    public MetricResultSet runAnalysis(List<CompilationUnit> compilationUnits) {
        return this.runAnalysis(compilationUnits, null);
    }
}
