package seng4430.parsing;

import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.resolution.SymbolResolver;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import com.github.javaparser.utils.SourceRoot;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

/**
 * Used to parse all java files within a provided project root.
 */
public class ProjectParser {

    /**
     * Parses the provided project root and configures symbol resolution for the compiled units.
     * @param rootPathString The path to the project directory to parse.
     * @param projectRootStrings The paths of any project files that need to be included for symbol resolution.
     * @return A list of {@link CompilationUnit} generated by parsing the project.
     * @throws IOException If the {@code rootPathString} cannot be found.
     */
    public static List<CompilationUnit> parse(String rootPathString, String... projectRootStrings) throws IOException {

        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();

        for (var path: projectRootStrings) {
            combinedTypeSolver.add(new JavaParserTypeSolver(new File(path)));
        }

        combinedTypeSolver.add(new ReflectionTypeSolver());

        SymbolResolver symbolResolver = new JavaSymbolSolver(combinedTypeSolver);
        ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setSymbolResolver(symbolResolver);

        Path directory = Paths.get(rootPathString);

        var projectRoot = new SourceRoot(directory);
        projectRoot.setParserConfiguration(parserConfiguration);

        projectRoot.tryToParse();

        return projectRoot.getCompilationUnits();
    }

    /**
     * Parses the provided project root and configures symbol resolution for the compiled units.
     * @param rootPathString The path to the project directory to parse. This path will also be used as the path for symbol resolution.
     * @return A list of {@link CompilationUnit} generated by parsing the project.
     * @throws IOException If the {@code rootPathString} cannot be found.
     */
    public static List<CompilationUnit> parse(String rootPathString) throws IOException {
        return parse(rootPathString, rootPathString);
    }
}
